Repository ProjectGoGym/BackEnd, pull requests merged in 2024-11, with the labels that each got.

#1 ✨ feat: 공통 사용 코드 구현
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/gogym/GoGymApplication.java
  src/main/java/com/gogym/common/entity/BaseEntity.java
  src/main/java/com/gogym/common/entity/BaseIdEntity.java
  src/main/java/com/gogym/common/response/ApplicationResponse.java
  src/main/java/com/gogym/common/response/ErrorCode.java
  src/main/java/com/gogym/common/response/ResponseCode.java
  src/main/java/com/gogym/common/response/SuccessCode.java
  src/main/java/com/gogym/config/JacksonConfig.java
  src/main/java/com/gogym/exception/CustomException.java
  src/main/java/com/gogym/exception/GlobalExceptionHandler.java
Labels: 🚀BE, ⚙️Setting

#11 ♻️ refactor: 공통 코드 수정, 로그 추가
  .gitignore
  build.gradle
  src/main/java/com/gogym/GoGymApplication.java
  src/main/java/com/gogym/aop/LoggingAspect.java
  src/main/java/com/gogym/common/response/ApplicationResponse.java
  src/main/java/com/gogym/exception/ErrorResponse.java
  src/main/java/com/gogym/exception/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: 🚀BE, ♻️Refactor

#12 feat : 회원 인증 관련 기능
  src/main/java/com/gogym/common/entity/BaseEntity.java
  src/main/java/com/gogym/common/entity/BaseIdEntity.java
  src/main/java/com/gogym/common/response/ErrorCode.java
  src/main/java/com/gogym/common/response/ResponseCode.java
  src/main/java/com/gogym/common/response/SuccessCode.java
  src/main/java/com/gogym/config/JwtAuthenticationFilter.java
  src/main/java/com/gogym/config/JwtTokenProvider.java
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/exception/CustomException.java
  src/main/java/com/gogym/exception/ErrorCode.java
  src/main/java/com/gogym/exception/ErrorResponse.java
  src/main/java/com/gogym/exception/GlobalExceptionHandler.java
  src/main/java/com/gogym/member/controller/AuthController.java
  src/main/java/com/gogym/member/controller/MemberController.java
  src/main/java/com/gogym/member/dto/MemberDto.java
  src/main/java/com/gogym/member/dto/ResetPasswordRequest.java
  src/main/java/com/gogym/member/dto/SignInRequest.java
  src/main/java/com/gogym/member/dto/SignUpRequest.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/member/entity/Role.java
  src/main/java/com/gogym/member/repository/MemberRepository.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/EmailService.java
  src/main/java/com/gogym/member/service/MemberService.java
  src/test/java/com/gogym/member/controller/AuthControllerTest.java
Labels: 🚀BE, ✨Feature, ♻️Refactor
