Repository ProjectGoGym/BackEnd, pull requests merged in 2024-12, with the labels that each got.

#32 ✨ feat : 채팅 메시지 브로드캐스팅 및 Redis-DB 연계 기능 구현
  build.gradle
  src/main/java/com/gogym/chat/controller/ChatController.java
  src/main/java/com/gogym/chat/controller/WebSocketChatController.java
  src/main/java/com/gogym/chat/dto/ChatDto.java
  src/main/java/com/gogym/chat/dto/ChatMessageDto.java
  src/main/java/com/gogym/chat/dto/ChatRoomDto.java
  src/main/java/com/gogym/chat/entity/ChatEntity.java
  src/main/java/com/gogym/chat/entity/ChatMessage.java
  src/main/java/com/gogym/chat/entity/ChatMessageRead.java
  src/main/java/com/gogym/chat/entity/ChatRoom.java
  src/main/java/com/gogym/chat/repository/ChatMessageReadRepository.java
  src/main/java/com/gogym/chat/repository/ChatMessageRepository.java
  src/main/java/com/gogym/chat/repository/ChatRepository.java
  src/main/java/com/gogym/chat/repository/ChatRoomRepository.java
  src/main/java/com/gogym/chat/schedule/ChatMessageBatchScheduler.java
  src/main/java/com/gogym/chat/service/ChatRedisService.java
  src/main/java/com/gogym/chat/service/ChatService.java
  src/main/java/com/gogym/chat/service/impl/ChatRedisServiceImpl.java
  src/main/java/com/gogym/config/RedisConfig.java
  src/main/java/com/gogym/config/WebSocketConfig.java
  src/main/java/com/gogym/exception/ErrorCode.java
  src/main/java/com/gogym/exception/ErrorResponse.java
  src/main/java/com/gogym/exception/GlobalExceptionHandler.java
  src/main/java/com/gogym/util/JsonUtil.java
  src/main/java/com/gogym/util/RedisUtil.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/test/java/com/gogym/chat/service/impl/ChatMessageBatchSchedulerTest.java
Labels: 🚀BE, ✨Feature

#30 ✨feat : 알림 관련 로직
  src/main/java/com/gogym/GoGymApplication.java
  src/main/java/com/gogym/aop/LoggingAspect.java
  src/main/java/com/gogym/notification/controller/NotificationController.java
  src/main/java/com/gogym/notification/dto/NotificationDto.java
  src/main/java/com/gogym/notification/entity/Notification.java
  src/main/java/com/gogym/notification/entity/NotificationEntity.java
  src/main/java/com/gogym/notification/repository/NotificationRepository.java
  src/main/java/com/gogym/notification/schedule/NotificationSchedule.java
  src/main/java/com/gogym/notification/service/NotificationService.java
  src/main/java/com/gogym/notification/type/NotificationType.java
  src/test/java/com/gogym/notification/service/NotificationServiceTest.java
Labels: 🚀BE, ✨Feature

#31 ✨ feat : 회원 인증 기능
  src/main/java/com/gogym/aop/LoginMemberIdHandler.java
  src/main/java/com/gogym/common/annotation/LoginMemberId.java
  src/main/java/com/gogym/config/WebConfig.java
  src/main/java/com/gogym/member/controller/AuthController.java
  src/main/java/com/gogym/member/dto/LoginResponse.java
  src/main/java/com/gogym/member/dto/ResetPasswordRequest.java
  src/main/java/com/gogym/member/dto/SignInRequest.java
  src/main/java/com/gogym/member/dto/SignUpRequest.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/member/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gogym/member/jwt/JwtTokenProvider.java
  src/main/java/com/gogym/member/jwt/SecurityConfig.java
  src/main/java/com/gogym/member/repository/MemberRepository.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/EmailService.java
  src/main/java/com/gogym/member/service/MemberService.java
  src/test/java/com/gogym/member/service/AuthServiceTest.java
Labels: 🚀BE, ✨Feature, ♻️Refactor

#35 ✨feat : 지역 등록 및 게시글 등록 구현
  src/main/java/com/gogym/post/controller/PostController.java
  src/main/java/com/gogym/post/dto/PostDto.java
  src/main/java/com/gogym/post/dto/PostRequestDto.java
  src/main/java/com/gogym/post/dto/PostResponseDto.java
  src/main/java/com/gogym/post/entity/Gym.java
  src/main/java/com/gogym/post/entity/Post.java
  src/main/java/com/gogym/post/entity/PostEntity.java
  src/main/java/com/gogym/post/repository/GymRepository.java
  src/main/java/com/gogym/post/repository/PostRepository.java
  src/main/java/com/gogym/post/service/PostService.java
  src/main/java/com/gogym/post/type/MembershipType.java
  src/main/java/com/gogym/post/type/PostStatus.java
  src/main/java/com/gogym/post/type/PostType.java
  src/main/java/com/gogym/region/controller/RegionController.java
  src/main/java/com/gogym/region/dto/RegionDto.java
  src/main/java/com/gogym/region/entity/Region.java
  src/main/java/com/gogym/region/repository/RegionRepository.java
  src/main/java/com/gogym/region/service/RegionService.java
  src/main/resources/data.sql
  src/test/java/com/gogym/notification/service/NotificationServiceTest.java
  src/test/java/com/gogym/post/service/PostServiceTest.java
  src/test/java/com/gogym/post/service/RegionServiceTest.java
Labels: 🚀BE, ✨Feature

#46 ♻️refactor : 알림 및 게시글 회원 정보(토큰) 가져오기 변경
  src/main/java/com/gogym/aop/LoggingAspect.java
  src/main/java/com/gogym/member/jwt/SecurityConfig.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/notification/controller/NotificationController.java
  src/main/java/com/gogym/notification/service/NotificationService.java
  src/main/java/com/gogym/post/controller/PostController.java
  src/main/java/com/gogym/post/service/PostService.java
  src/main/java/com/gogym/region/dto/RegionDto.java
  src/main/java/com/gogym/region/entity/Region.java
  src/test/java/com/gogym/notification/service/NotificationServiceTest.java
  src/test/java/com/gogym/post/service/PostServiceTest.java
  src/test/java/com/gogym/region/service/RegionServiceTest.java
Labels: 🚀BE, ♻️Refactor

#54 ✨ feat : 회원 인증 기능
  src/main/java/com/gogym/aop/LoginMemberIdHandler.java
  src/main/java/com/gogym/common/annotation/LoginMemberId.java
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/member/controller/AuthController.java
  src/main/java/com/gogym/member/dto/LoginResponse.java
  src/main/java/com/gogym/member/dto/SignInRequest.java
  src/main/java/com/gogym/member/dto/SignUpRequest.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/member/entity/Role.java
  src/main/java/com/gogym/member/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gogym/member/jwt/JwtTokenProvider.java
  src/main/java/com/gogym/member/repository/MemberRepository.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/EmailService.java
  src/main/java/com/gogym/member/service/MemberService.java
  src/main/java/com/gogym/util/RedisUtil.java
  src/test/java/com/gogym/member/service/AuthServiceTest.java
Labels: 🚀BE, ✨Feature

#55 ✨️feat : 게시글 조회 및 필터링 구현
  src/main/java/com/gogym/aop/LoginMemberIdHandler.java
  src/main/java/com/gogym/common/annotation/LoginMemberId.java
  src/main/java/com/gogym/config/QueryDslConfig.java
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/exception/ErrorCode.java
  src/main/java/com/gogym/notification/entity/Notification.java
  src/main/java/com/gogym/post/controller/PostController.java
  src/main/java/com/gogym/post/dto/PostFilterRequestDto.java
  src/main/java/com/gogym/post/dto/PostPageResponseDto.java
  src/main/java/com/gogym/post/dto/PostResponseDto.java
  src/main/java/com/gogym/post/entity/Post.java
  src/main/java/com/gogym/post/filter/PostFilterBuilder.java
  src/main/java/com/gogym/post/repository/PostRepository.java
  src/main/java/com/gogym/post/repository/PostRepositoryCustom.java
  src/main/java/com/gogym/post/repository/impl/PostRepositoryCustomImpl.java
  src/main/java/com/gogym/post/service/GymService.java
  src/main/java/com/gogym/post/service/PostService.java
  src/main/java/com/gogym/post/type/FilterMonthsType.java
  src/main/java/com/gogym/post/type/FilterPtType.java
  src/main/java/com/gogym/region/dto/RegionResponseDto.java
  src/main/java/com/gogym/region/service/RegionService.java
  src/test/java/com/gogym/post/service/GymServiceTest.java
  src/test/java/com/gogym/post/service/PostServiceTest.java
  src/test/java/com/gogym/region/service/RegionServiceTest.java
Labels: 🚀BE, ✨Feature

#59 ✨️feat : 채팅방 관리 기능 구현
  src/main/java/com/gogym/chat/controller/ChatRoomController.java
  src/main/java/com/gogym/chat/entity/ChatMessage.java
  src/main/java/com/gogym/chat/entity/ChatRoom.java
  src/main/java/com/gogym/chat/repository/ChatRoomRepository.java
  src/main/java/com/gogym/chat/service/ChatRedisService.java
  src/main/java/com/gogym/chat/service/ChatRoomService.java
  src/main/java/com/gogym/chat/service/impl/ChatRedisServiceImpl.java
  src/main/java/com/gogym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/gogym/config/WebSocketConfig.java
  src/main/java/com/gogym/util/RedisUtil.java
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
Labels: 🚀BE, ✨Feature

#60 ✨ feat: SSE, Webhook 사용한 잔액 충전 기능 개발
  src/main/java/com/gogym/aop/LoggingAspect.java
  src/main/java/com/gogym/config/WebClientConfig.java
  src/main/java/com/gogym/config/WebhookVerifierConfig.java
  src/main/java/com/gogym/gympay/controller/GymPayController.java
  src/main/java/com/gogym/gympay/controller/PaymentController.java
  src/main/java/com/gogym/gympay/dto/PaymentResult.java
  src/main/java/com/gogym/gympay/dto/TokenInfo.java
  src/main/java/com/gogym/gympay/dto/WebhookPayload.java
  src/main/java/com/gogym/gympay/dto/request/PreRegisterRequest.java
  src/main/java/com/gogym/gympay/dto/response/FailureResponse.java
  src/main/java/com/gogym/gympay/dto/response/PreRegisterResponse.java
  src/main/java/com/gogym/gympay/entity/GymPay.java
  src/main/java/com/gogym/gympay/entity/Payment.java
  src/main/java/com/gogym/gympay/entity/PaymentAmount.java
  src/main/java/com/gogym/gympay/entity/constant/Currency.java
  src/main/java/com/gogym/gympay/entity/constant/PaymentMethodType.java
  src/main/java/com/gogym/gympay/entity/constant/PgProvider.java
  src/main/java/com/gogym/gympay/entity/constant/SelectedChannelType.java
  src/main/java/com/gogym/gympay/entity/constant/Status.java
  src/main/java/com/gogym/gympay/entity/constant/WebhookStatus.java
  src/main/java/com/gogym/gympay/event/PaymentEventListener.java
  src/main/java/com/gogym/gympay/event/PaymentStatusChangedEvent.java
  src/main/java/com/gogym/gympay/repository/GymPayRepository.java
  src/main/java/com/gogym/gympay/repository/PaymentRepository.java
  src/main/java/com/gogym/gympay/service/GymPayService.java
  src/main/java/com/gogym/gympay/service/PaymentService.java
  src/main/java/com/gogym/gympay/service/PortOneService.java
  src/main/java/com/gogym/gympay/service/SSEService.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/util/RedisUtil.java
Labels: 🚀BE, ✨Feature

#63 ✨️feat : WebSocket 초기 연결 시 JWT 인증 로직 구현
  src/main/java/com/gogym/aop/LoggingAspect.java
  src/main/java/com/gogym/chat/controller/ChatRoomController.java
  src/main/java/com/gogym/chat/controller/WebSocketChatController.java
  src/main/java/com/gogym/chat/dto/ChatMessageDto.java
  src/main/java/com/gogym/chat/dto/ChatRoomDto.java
  src/main/java/com/gogym/chat/entity/ChatRoom.java
  src/main/java/com/gogym/chat/handler/StompHandler.java
  src/main/java/com/gogym/chat/repository/ChatRoomRepository.java
  src/main/java/com/gogym/chat/service/ChatRedisService.java
  src/main/java/com/gogym/chat/service/ChatRoomService.java
  src/main/java/com/gogym/chat/service/impl/ChatRedisServiceImpl.java
  src/main/java/com/gogym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/config/WebSocketConfig.java
  src/main/java/com/gogym/member/jwt/JwtAuthenticationFilter.java
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
Labels: 🚀BE, ✨Feature

#68 ♻️ refactor: ErrorCode에 WebSocket 인증 관련 예외 값 추가
  src/main/java/com/gogym/exception/ErrorCode.java
Labels: 🚀BE, ♻️Refactor

#69 ♻️ refactor: ChatMessageHistory 필드 자료형 수정으로 인한 테스트 코드 수정
  src/test/java/com/gogym/chat/service/impl/ChatMessageBatchSchedulerTest.java
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
Labels: 🚀BE, ♻️Refactor

#70 ♻️ refactor: Post 엔티티의 필드명 변경으로 인한 메서드 호출 로직 일부 수정
  src/main/java/com/gogym/chat/entity/ChatRoom.java
  src/main/java/com/gogym/chat/service/impl/ChatRoomServiceImpl.java
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
Labels: 🚀BE, ✨Feature

#71 ♻️ refactor: Post 엔티티 필드 이름 수정으로 인한 쿼리 수정
  src/main/java/com/gogym/chat/repository/ChatRoomRepository.java
Labels: 🚀BE, ♻️Refactor

#73 ✨feat : 게시글 상태를 반환하는 메서드 작성, 잘못된 import refactor
  src/main/java/com/gogym/post/repository/PostRepository.java
  src/main/java/com/gogym/post/service/PostService.java
Labels: 🚀BE, ✨Feature, ♻️Refactor

#75 ✨ feat : 카카오 로그인 기능
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/member/controller/KakaoController.java
  src/main/java/com/gogym/member/dto/KakaoProfileResponse.java
  src/main/java/com/gogym/member/dto/KakaoTokenResponse.java
  src/main/java/com/gogym/member/entity/KakaoMember.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/member/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gogym/member/repository/KakaoMemberRepository.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/KakaoService.java
  src/main/resources/application.yml
  src/test/java/com/gogym/member/service/AuthServiceTest.java
Labels: 🚀BE, ✨Feature

#78 ✨ Feat: 이미지 S3 업로드 구현
  build.gradle
  src/main/java/com/gogym/config/S3Config.java
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/exception/ErrorCode.java
  src/main/java/com/gogym/image/service/ImageController.java
  src/main/java/com/gogym/image/service/ImageService.java
Labels: 🚀BE, ✨Feature

#72 ✨️feat : 채팅방 메시지 및 게시물 상태 조회 기능 구현
  src/main/java/com/gogym/chat/controller/ChatMessageController.java
  src/main/java/com/gogym/chat/dto/ChatMessageDto.java
  src/main/java/com/gogym/chat/dto/ChatRoomDto.java
  src/main/java/com/gogym/chat/entity/ChatMessageRead.java
  src/main/java/com/gogym/chat/entity/ChatRoom.java
  src/main/java/com/gogym/chat/repository/ChatMessageReadRepository.java
  src/main/java/com/gogym/chat/repository/ChatMessageRepository.java
  src/main/java/com/gogym/chat/repository/ChatRoomRepository.java
  src/main/java/com/gogym/chat/schedule/ChatMessageBatchScheduler.java
  src/main/java/com/gogym/chat/service/ChatMessageService.java
  src/main/java/com/gogym/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/gogym/chat/service/impl/ChatRedisServiceImpl.java
  src/main/java/com/gogym/chat/service/impl/ChatRoomServiceImpl.java
  src/test/java/com/gogym/chat/service/impl/ChatMessageServiceImplTest.java
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
Labels: 🚀BE, ✨Feature

#76 ✨️feat : 프로필 및 활동 관리 기능
  src/main/java/com/gogym/member/controller/ActivityController.java
  src/main/java/com/gogym/member/controller/MemberController.java
  src/main/java/com/gogym/member/dto/MemberProfileResponse.java
  src/main/java/com/gogym/member/dto/SignUpRequest.java
  src/main/java/com/gogym/member/dto/UpdateMemberRequest.java
  src/main/java/com/gogym/member/entity/BanNickname.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/member/repository/BanNicknameRepository.java
  src/main/java/com/gogym/member/service/ActivityService.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/EmailService.java
  src/main/java/com/gogym/member/service/KakaoService.java
  src/main/java/com/gogym/member/service/MemberService.java
  src/main/java/com/gogym/member/type/MemberStatus.java
  src/test/java/com/gogym/member/service/ActivityServiceTest.java
  src/test/java/com/gogym/member/service/AuthServiceTest.java
  src/test/java/com/gogym/member/service/MemberServiceTest.java
Labels: 🚀BE, ✨Feature

#82 ✨ feat : 외부 도메인에서 사용할 메서드 구현 및 메시지 브로드캐스팅 로직 개선
  src/main/java/com/gogym/chat/controller/ChatMessageController.java
  src/main/java/com/gogym/chat/controller/WebSocketChatController.java
  src/main/java/com/gogym/chat/dto/ChatMessageDto.java
  src/main/java/com/gogym/chat/dto/MessageRequest.java
  src/main/java/com/gogym/chat/entity/ChatMessage.java
  src/main/java/com/gogym/chat/repository/ChatRoomRepository.java
  src/main/java/com/gogym/chat/schedule/ChatMessageBatchScheduler.java
  src/main/java/com/gogym/chat/service/ChatMessageQueryService.java
  src/main/java/com/gogym/chat/service/ChatMessageService.java
  src/main/java/com/gogym/chat/service/ChatRedisService.java
  src/main/java/com/gogym/chat/service/ChatRoomQueryService.java
  src/main/java/com/gogym/chat/service/ChatRoomService.java
  src/main/java/com/gogym/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/gogym/chat/service/impl/ChatRedisServiceImpl.java
  src/main/java/com/gogym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/gogym/chat/type/MessageType.java
  src/main/java/com/gogym/gympay/event/SendMessageEvent.java
  src/test/java/com/gogym/chat/service/impl/ChatMessageBatchSchedulerTest.java
  src/test/java/com/gogym/chat/service/impl/ChatMessageServiceImplTest.java
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/resources/test-data.sql
Labels: 🚀BE, ✨Feature, ♻️Refactor

#85 ✨feat : 게시글 상태를 변경하여 거래 상태를 변경하는 메서드 구현, 알림기능 refactor
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/config/WebConfig.java
  src/main/java/com/gogym/exception/ErrorCode.java
  src/main/java/com/gogym/gympay/event/listener/PaymentEventListener.java
  src/main/java/com/gogym/member/controller/AuthController.java
  src/main/java/com/gogym/member/controller/KakaoController.java
  src/main/java/com/gogym/member/dto/LoginResponse.java
  src/main/java/com/gogym/member/dto/ResetPasswordRequest.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/member/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/EmailService.java
  src/main/java/com/gogym/member/service/KakaoService.java
  src/main/java/com/gogym/notification/controller/NotificationController.java
  src/main/java/com/gogym/notification/service/NotificationService.java
  src/main/java/com/gogym/post/controller/PostController.java
  src/main/java/com/gogym/post/dto/PostResponseDto.java
  src/main/java/com/gogym/post/entity/Post.java
  src/main/java/com/gogym/post/repository/PostRepository.java
  src/main/java/com/gogym/post/service/PostService.java
  src/main/java/com/gogym/post/type/PostStatus.java
  src/main/resources/logback.xml
  src/test/java/com/gogym/member/service/AuthServiceTest.java
  src/test/java/com/gogym/member/service/MemberServiceTest.java
  src/test/java/com/gogym/notification/service/NotificationServiceTest.java
  src/test/java/com/gogym/post/service/PostServiceTest.java
  src/test/java/com/gogym/post/service/RecentViewServiceTest.java
  src/test/java/com/gogym/post/service/WishServiceTest.java
Labels: 🚀BE, ✨Feature, ♻️Refactor, ⚙️Setting

#87 ✨ Feat: 거래 일정 등록 및 거래 상태 변경에 따른 메서드 추가
  src/main/java/com/gogym/exception/ErrorCode.java
  src/main/java/com/gogym/gympay/controller/TransactionController.java
  src/main/java/com/gogym/gympay/dto/request/UpdateDateRequest.java
  src/main/java/com/gogym/gympay/entity/constant/TransactionStatus.java
  src/main/java/com/gogym/gympay/service/SafePaymentService.java
  src/main/java/com/gogym/gympay/service/TransactionService.java
Labels: ♻️Refactor

#95 🐛 fix: PostQueryService를 통한 의존성 분리로 순환 의존성 문제 해결
  src/main/java/com/gogym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/config/WebConfig.java
  src/main/java/com/gogym/exception/ErrorCode.java
  src/main/java/com/gogym/gympay/controller/TransactionController.java
  src/main/java/com/gogym/gympay/dto/request/UpdateDateRequest.java
  src/main/java/com/gogym/gympay/entity/constant/TransactionStatus.java
  src/main/java/com/gogym/gympay/event/listener/PaymentEventListener.java
  src/main/java/com/gogym/gympay/service/SafePaymentService.java
  src/main/java/com/gogym/gympay/service/TransactionService.java
  src/main/java/com/gogym/member/controller/AuthController.java
  src/main/java/com/gogym/member/controller/KakaoController.java
  src/main/java/com/gogym/member/dto/LoginResponse.java
  src/main/java/com/gogym/member/dto/ResetPasswordRequest.java
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/member/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/EmailService.java
  src/main/java/com/gogym/member/service/KakaoService.java
  src/main/java/com/gogym/notification/controller/NotificationController.java
  src/main/java/com/gogym/notification/service/NotificationService.java
  src/main/java/com/gogym/post/controller/PostController.java
  src/main/java/com/gogym/post/dto/PostResponseDto.java
  src/main/java/com/gogym/post/entity/Post.java
  src/main/java/com/gogym/post/repository/PostRepository.java
  src/main/java/com/gogym/post/service/PostQueryService.java
  src/main/java/com/gogym/post/service/PostQueryServiceImpl.java
  src/main/java/com/gogym/post/service/PostService.java
  src/main/java/com/gogym/post/service/WishService.java
  src/main/java/com/gogym/post/type/PostStatus.java
  src/main/resources/logback.xml
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
  src/test/java/com/gogym/member/service/AuthServiceTest.java
  src/test/java/com/gogym/member/service/MemberServiceTest.java
  src/test/java/com/gogym/notification/service/NotificationServiceTest.java
  src/test/java/com/gogym/post/service/PostServiceTest.java
  src/test/java/com/gogym/post/service/RecentViewServiceTest.java
  src/test/java/com/gogym/post/service/WishServiceTest.java
Labels: 🚀BE, 🐞BugFix

#105 ♻️refactor : 알림관련 로직 수정
  src/main/java/com/gogym/exception/GlobalExceptionHandler.java
  src/main/java/com/gogym/notification/service/NotificationService.java
Labels: 🚀BE, ♻️Refactor, ⚙️Setting

#99 ♻️ refactor: 안전결제 도메인 리팩터링
  src/main/java/com/gogym/gympay/controller/GymPayController.java
  src/main/java/com/gogym/gympay/controller/PaymentController.java
  src/main/java/com/gogym/gympay/controller/SafePaymentController.java
  src/main/java/com/gogym/gympay/controller/TransactionController.java
  src/main/java/com/gogym/gympay/dto/PaymentResult.java
  src/main/java/com/gogym/gympay/dto/WebhookPayload.java
  src/main/java/com/gogym/gympay/dto/request/SafePaymentRequest.java
  src/main/java/com/gogym/gympay/dto/response/GetHistory.java
  src/main/java/com/gogym/gympay/entity/GymPayHistory.java
  src/main/java/com/gogym/gympay/entity/SafePayment.java
  src/main/java/com/gogym/gympay/entity/Transaction.java
  src/main/java/com/gogym/gympay/entity/constant/TransferType.java
  src/main/java/com/gogym/gympay/event/SendMessageEvent.java
  src/main/java/com/gogym/gympay/repository/GymPayHistoryRepository.java
  src/main/java/com/gogym/gympay/repository/GymPayHistoryRepositoryCustom.java
  src/main/java/com/gogym/gympay/repository/TransactionRepository.java
  src/main/java/com/gogym/gympay/repository/TransactionRepositoryCustom.java
  src/main/java/com/gogym/gympay/repository/impl/GymPayHistoryRepositoryImpl.java
  src/main/java/com/gogym/gympay/repository/impl/TransactionRepositoryImpl.java
  src/main/java/com/gogym/gympay/service/GymPayHistoryService.java
  src/main/java/com/gogym/gympay/service/GymPayService.java
  src/main/java/com/gogym/gympay/service/PaymentService.java
  src/main/java/com/gogym/gympay/service/SafePaymentService.java
  src/main/java/com/gogym/gympay/service/TransactionService.java
  src/main/java/com/gogym/gympay/service/strategy/PaymentPaidStrategy.java
  src/main/java/com/gogym/member/controller/ActivityController.java
  src/main/java/com/gogym/post/controller/PostController.java
  src/main/java/com/gogym/post/dto/PostPageResponseDto.java
  src/main/java/com/gogym/post/service/PostService.java
  src/main/java/com/gogym/transaction/controller/TransactionController.java
  src/main/java/com/gogym/transaction/dto/TransactionDto.java
  src/main/java/com/gogym/transaction/entity/TransactionEntity.java
  src/main/java/com/gogym/transaction/repository/TransactionRepository.java
  src/main/java/com/gogym/transaction/service/TransactionService.java
Labels: 🚀BE, ♻️Refactor

#110 ♻️refactor : sse 구독 서비스 로그 변경, 게시글 반환 값 post type 추가
  src/main/java/com/gogym/gympay/repository/impl/TransactionRepositoryImpl.java
  src/main/java/com/gogym/notification/service/NotificationService.java
  src/main/java/com/gogym/post/dto/PostPageResponseDto.java
  src/main/java/com/gogym/post/repository/PostRepository.java
  src/main/java/com/gogym/post/service/PostService.java
  src/test/java/com/gogym/post/service/PostServiceTest.java
Labels: 🚀BE, ♻️Refactor

#111 ♻️refactor : 게시글, 멤버 엔티티 수정
  src/main/java/com/gogym/member/entity/Member.java
  src/main/java/com/gogym/post/entity/Post.java
  src/main/java/com/gogym/post/service/PostService.java
Labels: 🚀BE, ♻️Refactor

#124 ✨ feat: 채팅방 목록 조회 쿼리 개선 및 초기 메시지 브로드캐스팅 기능 추가
  src/main/java/com/gogym/chat/dto/base/RedisMessage.java
  src/main/java/com/gogym/chat/event/ChatRoomEvent.java
  src/main/java/com/gogym/chat/event/listener/ChatRoomEventListener.java
  src/main/java/com/gogym/chat/repository/ChatRoomRepository.java
  src/main/java/com/gogym/chat/service/impl/ChatRoomServiceImpl.java
  src/test/java/com/gogym/chat/service/impl/ChatRoomServiceImplTest.java
Labels: 🚀BE, 🐞BugFix, ✨Feature

#133 ♻️refactor : 게시글 조회시 알수없는 에러 수정
  src/main/java/com/gogym/post/repository/RecentViewRepository.java
Labels: 🚀BE, 🐞BugFix, ♻️Refactor

#136 ♻️ refactor: 카카오 기능 리팩토링
  src/main/java/com/gogym/config/SecurityConfig.java
  src/main/java/com/gogym/member/controller/AuthController.java
  src/main/java/com/gogym/member/controller/KakaoController.java
  src/main/java/com/gogym/member/dto/KakaoLoginResponse.java
  src/main/java/com/gogym/member/service/AuthService.java
  src/main/java/com/gogym/member/service/KakaoService.java
Labels: 🚀BE, ✨Feature

#137 🐞 fix: Jackson Config에 time zone 설정
  src/main/java/com/gogym/config/JacksonConfig.java
  src/main/java/com/gogym/image/controller/ImageController.java
Labels: 🚀BE, ♻️Refactor

#140 ♻️ refactor: 거래날짜 등록 시 Message 전송 추가
  src/main/java/com/gogym/gympay/controller/TransactionController.java
  src/main/java/com/gogym/gympay/service/TransactionService.java
Labels: 🚀BE, ♻️Refactor
